test

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -30,6 +30,13 @@ jobs:
     - run: npx parcel build
     - run: npm run dev &
     - run: npm run test
+    - run: |
+        if [ "$allTestsPassed" = "false" ]; then
+          echo "Some tests failed."
+          exit 1
+        fi
+      env:
+          allTestsPassed: ${{ env.allTestsPassed }}
     - uses: actions/upload-artifact@v4
       with:
         name: my-artifact
